# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

AUTHOR: Faith Paule
DATE: 2026

Topic: Data Science & Web Scraping - Web scraping, Data Processing, Data Visualization, COVID-19 simulation
Identification: Web scraping population data from a website, processing it with pandas, filtering by population thresholds, generating synthetic COVID-19 data, and creating comprehensive data visualizations (scatter plots, line graphs, bar charts, pie charts, histograms) using matplotlib.
Programming Language: Python 3

Tech Stack:
- Requests - HTTP requests for web scraping
- BeautifulSoup4 - HTML parsing
- Pandas - Data manipulation and analysis
- NumPy - Numerical operations and random data generation
- Matplotlib - Data visualization
- Google Colab - Jupyter notebook environment
- Dasma Population and COVID-19 Data Analysis
"""

# ============================================================================
# PART 1: WEB SCRAPING - Dasmarinas Barangay Population Data
# ============================================================================

# Install pandas if not already installed
!pip install pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the webpage barangay population data
url = 'https://www.citypopulation.de/en/philippines/dasmarinas/'

# Fetch the HTML content from the URL
response = requests.get(url)
html_content = response.text

# Parse HTML using BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Find the population data table by its class name
table = soup.find('table', {'class': 'data'})

# Extract table rows
rows = table.find_all('tr')

# Initialize list to hold barangay data
barangay_data = []

# Iterate through each row, skipping the header
for row in rows[1:]:
    columns = row.find_all('td')
    if not columns:
        continue  # Skip empty rows

    # Extract data from columns
    barangay_name = columns[0].get_text(strip=True)
    status = columns[1].get_text(strip=True)
    population_2000 = columns[2].get_text(strip=True)
    population_2010 = columns[3].get_text(strip=True)
    population_2015 = columns[4].get_text(strip=True)
    population_2020 = columns[5].get_text(strip=True)

    # Append data to the list
    barangay_data.append({
        "Barangay Name": barangay_name,
        "Status": status,
        "Population in 2000": population_2000,
        "Population in 2010": population_2010,
        "Population in 2015": population_2015,
        "Population in 2020": population_2020
    })

# Convert list of dictionaries to DataFrame
df = pd.DataFrame(barangay_data)

# Save DataFrame to CSV
df.to_csv('dasma_barangay_population.csv', index=False)

# ============================================================================
# PART 2: DATA CLEANING AND FILTERING
# ============================================================================

# Reload the data from CSV
df = pd.read_csv('dasma_barangay_population.csv')

# Clean 'Population in 2020' column and convert to numeric
df['Population in 2020'] = pd.to_numeric(df['Population in 2020'].replace({',': ''}, regex=True), errors='coerce')

# Remove rows with NaN values in 'Population in 2020'
df = df.dropna(subset=['Population in 2020'])

# Filter barangays with populations greater than 10,000
df_greater_than_10000 = df[df['Population in 2020'] > 10000]
df_greater_than_10000.to_csv('dasma_greater_than_10000_in_2020.csv', index=False)

# Filter barangays with populations 10,000 or less
df_less_than_10000 = df[df['Population in 2020'] <= 10000]
df_less_than_10000.to_csv('dasma_less_than_10000_in_2020.csv', index=False)

# Confirm data export completion
print("Data export complete.")

# ============================================================================
# PART 3: COVID-19 DATA SIMULATION AND VISUALIZATION
# ============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display plots inline in Jupyter notebooks
# %matplotlib inline

def process_covid_data(input_file, output_file, population_group):
    """
    Generate synthetic COVID-19 data and create visualizations.
    
    Args:
        input_file: CSV file with barangay names
        output_file: Output CSV for generated data
        population_group: Label for charts (e.g., "More than 10,000 Population")
    
    Visualizations:
        1. Scatter plot: Confirmed Cases vs Recoveries
        2. Line graph: Cases, Recoveries, Deaths by Barangay
        3. Bar chart: Cases, Recoveries, Deaths by Barangay
        4. Pie chart: Proportions of total cases/recoveries/deaths
        5. Histogram: Distribution of cases, recoveries, deaths
    """
    # Load data from CSV
    df = pd.read_csv(input_file)

    # Generate random COVID-19 data
    df['ConfirmedCases'] = np.random.randint(50, 5000, size=len(df))
    df['Recoveries'] = df['ConfirmedCases'] - np.random.randint(0, df['ConfirmedCases'] // 2, size=len(df))
    df['Deaths'] = np.random.randint(0, df['ConfirmedCases'] // 4, size=len(df))

    # Save generated data to new CSV
    df.to_csv(output_file, index=False)

    # 1. Scatter Plot: Confirmed Cases vs Recoveries
    plt.figure(figsize=(8, 6))
    plt.scatter(df['ConfirmedCases'], df['Recoveries'], color='blue')
    plt.title(f'Confirmed Cases vs Recoveries - {population_group}')
    plt.xlabel('Confirmed Cases')
    plt.ylabel('Recoveries')
    plt.grid(True)
    plt.show()

    # 2. Line Graph: Cases, Recoveries, Deaths by Barangay
    plt.figure(figsize=(10, 6))
    plt.plot(df['Barangay Name'], df['ConfirmedCases'], label='Confirmed Cases', marker='o', color='blue')
    plt.plot(df['Barangay Name'], df['Recoveries'], label='Recoveries', marker='o', color='green')
    plt.plot(df['Barangay Name'], df['Deaths'], label='Deaths', marker='o', color='red')
    plt.xticks(rotation=90)
    plt.title(f'COVID-19 Data by Barangay - {population_group}')
    plt.xlabel('Barangay')
    plt.ylabel('Count')
    plt.legend()
    plt.show()

    # 3. Bar Graph: Cases, Recoveries, Deaths by Barangay
    plt.figure(figsize=(12, 6))
    bar_width = 0.25
    bar_positions = np.arange(len(df['Barangay Name']))
    plt.bar(bar_positions, df['ConfirmedCases'], color='purple', width=bar_width, label='Confirmed Cases')
    plt.bar(bar_positions + bar_width, df['Recoveries'], color='green', width=bar_width, label='Recoveries')
    plt.bar(bar_positions + 2 * bar_width, df['Deaths'], color='red', width=bar_width, label='Deaths')
    plt.xticks(bar_positions + bar_width, df['Barangay Name'], rotation=90)
    plt.title(f'COVID-19 Data by Barangay - {population_group}')
    plt.xlabel('Barangay')
    plt.ylabel('Count')
    plt.legend()
    plt.tight_layout()
    plt.show()

    # 4. Pie Chart: Proportions of Cases, Recoveries, Deaths
    labels = ['Confirmed Cases', 'Recoveries', 'Deaths']
    sizes = [df['ConfirmedCases'].sum(), df['Recoveries'].sum(), df['Deaths'].sum()]
    colors = ['blue', 'green', 'red']
    plt.figure(figsize=(6, 6))
    plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
    plt.title(f'COVID-19 Proportions - {population_group}')
    plt.show()

    # 5. Histograms: Distribution of Cases, Recoveries, Deaths
    plt.figure(figsize=(6, 5))
    plt.hist(df['ConfirmedCases'], bins=10, color='blue', edgecolor='black', alpha=0.5, label='Confirmed Cases')
    plt.hist(df['Recoveries'], bins=10, color='green', edgecolor='black', alpha=0.5, label='Recoveries')
    plt.hist(df['Deaths'], bins=10, color='red', edgecolor='black', alpha=0.5, label='Deaths')
    plt.title(f'Distribution of Cases, Recoveries, Deaths - {population_group}')
    plt.xlabel('Count')
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(True)
    plt.show()

# Process and visualize data for both population groups
process_covid_data('dasma_greater_than_10000_in_2020.csv', 'covid_data_greater_than_10000.csv', 'More than 10,000 Population')
process_covid_data('dasma_less_than_10000_in_2020.csv', 'covid_data_less_than_10000.csv', 'Less than 10,000 Population')
