# -*- coding: utf-8 -*-
"""pang_algo_NutriAI-D - Personalized Meal and Workout Recommendation System

Automatically generated by Colab.
AUTHOR: Faith Paule
DATE:

PROGRAM: NutriAI-D
TOPIC: Data Science / Health Analytics - Personalized Recommendation System, BMI Analysis, Greedy Optimization, Dietary Planning (Greedy Algorithm)
DESCRIPTION Building NutriAI-D, a personalized meal and workout recommendation system that:
- Calculates BMI from user input (weight, height)
- Classifies BMI into Underweight/Normal/Overweight
- Uses a greedy algorithm to select optimal meals based on calorie targets, macronutrients, dietary restrictions, and user preferences
- Suggests workouts based on BMI category
- Outputs recommendations in a formatted table
- Respects dietary restrictions and user preferences

Programming Language: Python 3

Tech Stack:
- Pandas - Data manipulation and CSV loading
- Tabulate - Formatted table output (grid format)
- Python Standard Library - File I/O, math operations
- Google Colab - Jupyter notebook environment

DATA FILES:
- bld.csv: Meal data with calories, protein, fat, carbohydrates, category
- workout1.csv: Exercise data with duration and calorie burn estimates
"""

import pandas as pd
from tabulate import tabulate

# ============================================================================
# DATA LOADING
# ============================================================================
# Load meal and workout datasets with latin-1 encoding for special characters
meal_data = pd.read_csv('bld.csv', encoding='latin-1')
workout_data = pd.read_csv('workout1.csv', encoding='latin-1')

# ============================================================================
# BMI CLASSIFICATION FUNCTION
# ============================================================================
def classify_bmi(weight, height):
    """
    Calculate BMI and classify into categories.
    
    BMI Formula: weight (kg) / height (m)²
    Categories:
    - Underweight: BMI < 18.5
    - Normal: 18.5 ≤ BMI < 24.9
    - Overweight: BMI ≥ 25
    
    Args:
        weight: Weight in kilograms
        height: Height in centimeters
    
    Returns:
        tuple: (bmi_value, category_string)
    """
    # Convert height from cm to meters
    height_m = height / 100
    bmi = weight / (height_m ** 2)
    
    # Classify BMI
    if bmi < 18.5:
        category = 'Underweight'
    elif 18.5 <= bmi < 24.9:
        category = 'Normal'
    else:
        category = 'Overweight'
    
    return bmi, category


# ============================================================================
# USER PROFILE (with example values)
# ============================================================================
user_profile = {
    # Calorie targets per meal (min, max)
    'calorie_target': {
        'Breakfast': (300, 600),
        'Lunch': (500, 700),
        'Dinner': (500, 700)
    },
    'protein_target': 1.2,      # Grams per kg of body weight
    'fat_target': 0.3,          # Grams per kg of body weight
    'carbohydrate_target': 0.5, # Grams per kg of body weight
    'restrictions': ['dairy', 'gluten'],  # Foods to avoid
    'preferences': ['fruits', 'vegetables', 'lean protein']  # Preferred foods
}

# ============================================================================
# FITNESS SCORE CALCULATION
# ============================================================================
def calculate_fitness_score(meal, user_profile, weight):
    """
    Calculate fitness score for a meal based on multiple criteria.
    
    Scoring Components:
    1. Calorie target adherence (negative penalty for deviation)
    2. Macronutrient targets (protein, fat, carbs)
    3. Dietary restrictions (large penalty if violated)
    4. User preferences (bonus points for preferred foods)
    
    Args:
        meal: Meal data (Series)
        user_profile: User preferences dictionary
        weight: User's weight in kg
    
    Returns:
        int/float: Fitness score (higher = better fit)
    """
    score = 0
    
    # 1. Calorie Target Adherence
    target_min, target_max = user_profile['calorie_target'][meal['Category']]
    ideal_calorie = (target_min + target_max) / 2
    calorie_diff = abs(meal['Calories (kcal)'] - ideal_calorie)
    score -= calorie_diff  # Penalize deviation from ideal
    
    # 2. Macronutrient Targets
    protein_target = user_profile['protein_target'] * weight
    fat_target = user_profile['fat_target'] * weight
    carb_target = user_profile['carbohydrate_target'] * weight
    
    score -= abs(meal['Protein (g)'] - protein_target)
    score -= abs(meal['Fat (g)'] - fat_target)
    score -= abs(meal['Carbohydrate (g)'] - carb_target)
    
    # 3. Dietary Restrictions (high penalty)
    for restriction in user_profile['restrictions']:
        if restriction in str(meal['Description']).lower():
            score -= 100  # Heavy penalty for restricted foods
    
    # 4. User Preferences (bonus points)
    for preference in user_profile['preferences']:
        if preference in str(meal['Description']).lower():
            score += 10  # Bonus for preferred foods
    
    return score


# ============================================================================
# GREEDY MEAL SELECTION ALGORITHM
# ============================================================================
def select_meal_greedy(category, meal_data, user_profile, weight):
    """
    Select best meal for a category using greedy approach.
    
    Greedy strategy: Choose meal with highest fitness score.
    
    Args:
        category: Meal category (Breakfast, Lunch, Dinner)
        meal_data: DataFrame containing all meals
        user_profile: User preferences dictionary
        weight: User's weight in kg
    
    Returns:
        DataFrame with selected meal
    """
    # Filter meals by category
    category_data = meal_data[meal_data['Category'] == category]
    
    # Find meal with highest fitness score
    best_meal = None
    best_score = -float('inf')
    
    for index, meal in category_data.iterrows():
        score = calculate_fitness_score(meal, user_profile, weight)
        if score > best_score:
            best_score = score
            best_meal = meal
    
    return pd.DataFrame([best_meal])


# ============================================================================
# WORKOUT SUGGESTION FUNCTION
# ============================================================================
def suggest_workouts(bmi_category, workout_data):
    """
    Suggest random workouts based on BMI category.
    
    Different calorie burn columns for each category:
    - Underweight: 'U - Calories Burnt (kcal)'
    - Normal: 'N - Calories Burnt (kcal)'
    - Overweight: 'O - Calories Burnt (kcal)'
    
    Args:
        bmi_category: 'Underweight', 'Normal', or 'Overweight'
        workout_data: DataFrame containing workout information
    
    Returns:
        DataFrame with 3 random workout suggestions
    """
    # Select appropriate calorie column based on BMI
    if bmi_category == 'Underweight':
        calorie_column = 'U - Calories Burnt (kcal)'
    elif bmi_category == 'Normal':
        calorie_column = 'N - Calories Burnt (kcal)'
    else:  # Overweight
        calorie_column = 'O - Calories Burnt (kcal)'
    
    # Randomly sample 3 workouts
    workouts = workout_data.sample(n=3)
    suggested_workouts = workouts[['Exercise', 'Description', 'Duration (mins)', calorie_column]]
    
    return suggested_workouts


# ============================================================================
# MAIN PROGRAM
# ============================================================================
print("=" * 60)
print("NUTRIAI-D: Personalized Meal & Workout Recommender")
print("=" * 60)

# Get user input for BMI calculation
weight = float(input("\nEnter your weight in kg: "))
height = float(input("Enter your height in cm: "))

# Calculate and classify BMI
bmi, user_bmi_category = classify_bmi(weight, height)

# Suggest meals using greedy algorithm
print("\n" + "=" * 60)
print("ANALYZING OPTIMAL MEALS...")
print("=" * 60)

suggested_meals = []
for category in ['Breakfast', 'Lunch', 'Dinner']:
    suggested_meals.append(select_meal_greedy(category, meal_data, user_profile, weight))
suggested_meals = pd.concat(suggested_meals)

# Suggest workouts based on BMI category
suggested_workouts = suggest_workouts(user_bmi_category, workout_data)

# ============================================================================
# OUTPUT RESULTS
# ============================================================================
print(f"\n📊 YOUR BMI RESULTS")
print("-" * 40)
print(f"   BMI: {bmi:.2f}")
print(f"   Classification: {user_bmi_category}")

print(f"\n🍽️ SUGGESTED MEALS")
print("-" * 40)
print(tabulate(suggested_meals, headers='keys', tablefmt='grid', showindex=False))

print(f"\n💪 SUGGESTED WORKOUTS")
print("-" * 40)
print(tabulate(suggested_workouts, headers='keys', tablefmt='grid', showindex=False))

print("\n✅ Recommendations generated successfully!")
