# -*- coding: utf-8 -*-
"""Paule_CSIS111_PandasAndDataFrame - Population and COVID-19 Data Analysis

Automatically generated by Colab.

AUTHOR: Faith Paule
COURSE: BCS35 | S-CSIS311
DATE: Due September 13, 2024
TOPIC: Data Science / Data Analysis - Pandas DataFrame operations, Data filtering, Matplotlib visualization
PROGRAM: Pandas DataFrame Population & COVID-19 Analysis
IDENTIFICATION: Creating a data analysis and visualization program that:
- Reads population data from an Excel file (Dasmariñas barangay census data)
- Filters and displays barangays with populations above/below 10,000
- Creates a COVID-19 dataset for Cavite cities
- Generates 5 types of visualizations (Scatter plot, Line graph, Bar graph, Pie chart, Histogram)

Programming Language: Python 3

Tech Stack:
- Pandas - Data manipulation and analysis (DataFrame, reading Excel)
- Matplotlib - Data visualization (scatter, line, bar, pie, histogram)
- openpyxl - Excel file engine for reading .xlsx files
- Google Colab - Jupyter notebook environment
"""

import pandas as pd
import matplotlib.pyplot as plt

# ============================================================================
# PART 1: LOAD AND PROCESS POPULATION DATA (Dasmariñas Barangays)
# ============================================================================

# Define the path to your Excel file
# NOTE: For Google Colab, upload file first and use filename only
file_path = r'D:\Local C files\Documents\Dasmariñas.xlsx'  # Windows path

# Load the Excel file into a Pandas DataFrame
data = pd.read_excel(file_path, engine='openpyxl')

# Use the latest population census column
population_column = 'Population Census 2020-05-01'

# Check if the population column exists
if population_column in data.columns:
    # Convert population column to numeric (handles non-numeric values as NaN)
    data[population_column] = pd.to_numeric(data[population_column], errors='coerce')

    # Remove rows with missing population data
    data = data.dropna(subset=[population_column])

    # Filter barangays with population > 10,000
    pop_greater_10000 = data[data[population_column] > 10000]
    print("Barangays with populations greater than 10,000 (2020 Census):")
    for index, row in pop_greater_10000.iterrows():
        print(f"\t- {row['Name']}: {row[population_column]}")

    # Filter barangays with population < 10,000
    print("\nBarangays with populations less than 10,000 (2020 Census):")
    pop_less_10000 = data[data[population_column] < 10000]
    for index, row in pop_less_10000.iterrows():
        print(f"\t- {row['Name']}: {row[population_column]}")
else:
    print(f"Error: '{population_column}' column not found in the dataset.")

# ============================================================================
# PART 2: CREATE COVID-19 DATA FOR CAVITE CITIES
# ============================================================================

# Sample data for COVID-19 cases in Cavite
covid_data = {
    'Cavite': ['Trece Martires City', 'Dasmariñas', 'General Trias', 'Imus', 'Bacoor'],
    'Confirmed Cases': [700, 350, 250, 600, 400],
    'Recoveries': [300, 250, 100, 150, 350],
    'Deaths': [50, 25, 15, 20, 10]
}

# Create DataFrame from dictionary
df = pd.DataFrame(covid_data)

print("\nStatistical Data in Cavite to Track COVID-19 Cases:")
print(df)
print()

# ============================================================================
# PART 3: DATA VISUALIZATIONS (5 Types)
# ============================================================================

# 1. SCATTER PLOT - Shows individual data points
plt.figure(figsize=(8, 5))
plt.scatter(df['Cavite'], df['Confirmed Cases'], color='blue', label='Confirmed Cases')
plt.scatter(df['Cavite'], df['Recoveries'], color='green', label='Recoveries')
plt.scatter(df['Cavite'], df['Deaths'], color='red', label='Deaths')
plt.xlabel('Cavite')
plt.ylabel('Count')
plt.title('COVID-19 Data: Scatter Plot')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# 2. LINE GRAPH - Shows trends across categories
plt.figure(figsize=(8, 5))
plt.plot(df['Cavite'], df['Confirmed Cases'], marker='o', color='blue', label='Confirmed Cases')
plt.plot(df['Cavite'], df['Recoveries'], marker='o', color='green', label='Recoveries')
plt.plot(df['Cavite'], df['Deaths'], marker='o', color='red', label='Deaths')
plt.xlabel('Cavite')
plt.ylabel('Count')
plt.title('COVID-19 Data: Line Graph')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# 3. BAR GRAPH - Grouped bars for comparison
plt.figure(figsize=(8, 5))
bar_width = 0.2
index = range(len(df['Cavite']))

plt.bar(index, df['Confirmed Cases'], bar_width, label='Confirmed Cases', color='blue')
plt.bar([i + bar_width for i in index], df['Recoveries'], bar_width, label='Recoveries', color='green')
plt.bar([i + 2 * bar_width for i in index], df['Deaths'], bar_width, label='Deaths', color='red')

plt.xlabel('Cavite')
plt.ylabel('Count')
plt.title('COVID-19 Data: Bar Graph')
plt.xticks([i + bar_width for i in index], df['Cavite'], rotation=45)
plt.legend()
plt.grid(True, axis='y')
plt.tight_layout()
plt.show()

# 4. PIE CHART - Shows proportions of total cases/recoveries/deaths
total_cases = df[['Confirmed Cases', 'Recoveries', 'Deaths']].sum()
labels = total_cases.index
sizes = total_cases.values

plt.figure(figsize=(8, 5))
plt.pie(sizes, labels=labels, autopct='%1.1f%%', colors=['blue', 'green', 'red'])
plt.title('COVID-19 Data: Pie Chart')
plt.show()

# 5. HISTOGRAM - Shows frequency distribution
plt.figure(figsize=(8, 5))
plt.hist(df['Confirmed Cases'], bins=5, alpha=0.7, color='blue', label='Confirmed Cases')
plt.hist(df['Recoveries'], bins=5, alpha=0.7, color='green', label='Recoveries')
plt.hist(df['Deaths'], bins=5, alpha=0.7, color='red', label='Deaths')
plt.xlabel('Count')
plt.ylabel('Frequency')
plt.title('COVID-19 Data: Histogram')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
